name: Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org/'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Install dependencies
        run: pnpm install
      - run: pnpm dev:prepare
      - name: Publish Package
        run: pnpm publish --access public --no-git-checks --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
